# 3 章ニューラルネットワーク

## 3.3 多次元配列の計算

### 3.3.1 多次元配列

In [9]:
import numpy as np

In [2]:
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [3]:
np.ndim(A)

1

In [4]:
A.shape

(4,)

In [5]:
A.shape[0]

4

In [6]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
np.ndim(B)

2

In [8]:
B.shape

(3, 2)

### 3.3.2 行列の積

In [9]:
A = np.array([[1,2], [3,4]])
A.shape

(2, 2)

In [10]:
B = np.array([[5,6], [7,8]])
B.shape

(2, 2)

In [11]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [12]:
A = np.array([[1,2,3], [4,5,6]])
A.shape

(2, 3)

In [13]:
B = np.array([[1,2], [3,4], [5,6]])
B.shape

(3, 2)

In [14]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [15]:
A = np.array([[1,2], [3,4], [5,6]])
A.shape

(3, 2)

In [16]:
B = np.array([7,8])
B.shape

(2,)

In [17]:
np.dot(A,B)

array([23, 53, 83])

### 3.3.3 ニューラルネットワークの行列の積

In [18]:
X = np.array([1,2])
X.shape

(2,)

In [19]:
W = np.array([[1,3,5], [2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [20]:
W.shape

(2, 3)

In [21]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]


## 3.4 3 層ニューラルネットワークの実装

### 3.4.2 各層における信号伝達の実装

In [23]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])
print(W1.shape)
print(X.shape)
print(B1.shape)

(2, 3)
(2,)
(3,)


In [25]:
A1 = np.dot(X, W1) + B1
print(A1)

[ 0.3  0.7  1.1]


In [11]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [27]:
Z1 = sigmoid(A1)
print(Z1)

[ 0.57444252  0.66818777  0.75026011]


In [28]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])
print(Z1.shape)
print(W2.shape)
print(B2.shape)

(3,)
(3, 2)
(2,)


In [29]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

In [30]:
def identity_function(x):
    return x

In [31]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

In [32]:
A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)

### 3.4.3 実装のまとめ

In [33]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    
    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)

[ 0.31682708  0.69627909]


## 3.5.2 ソフトマックス関数の実装上の注意

In [13]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

## 3.6 手書き数字認識

### 3.6.1 MNIST データセット

In [2]:
import sys, os
sys.path.append(os.pardir)
from dataset.mnist import load_mnist

In [35]:
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

Done
Done
Done
Done
Converting train-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting train-labels-idx1-ubyte.gz to NumPy Array ...
Done
Converting t10k-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting t10k-labels-idx1-ubyte.gz to NumPy Array ...
Done
Creating pickle file ...
Done!


In [36]:
print(x_train.shape)
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [37]:
from PIL import Image

In [38]:
def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()

In [39]:
img = x_train[0]
label = t_train[0]
print(label)

5


In [40]:
print(img.shape)
img = img.reshape(28, 28)
print(img.shape)

(784,)
(28, 28)


In [44]:
img_show(img)

### 3.6.2 ニューラルネットワークの推論処理

In [6]:
import pickle

In [3]:
def get_data():
    (x_train, t_train), (x_test, t_test) = load_mnist(normalize=True, flatten=True, one_hot_label=False)
    return x_test, t_test

def init_network():
    with open("sample_weight.pkl", 'rb') as f:
        network = pickle.load(f)
        
    return network

def predict(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)
    
    return y

In [7]:
x, t = get_data()
network = init_network()

In [14]:
accuracy_cnt = 0
for i in range(len(x)):
    y = predict(network, x[i])
    p = np.argmax(y)
    if p == t[i]:
        accuracy_cnt += 1
        
print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

Accuracy:0.9352


### 3.6.3 バッチ処理

In [15]:
x, _ = get_data()
network = init_network()
W1, W2, W3 = network['W1'], network['W2'], network['W3']

In [16]:
x.shape

(10000, 784)

In [17]:
x[0].shape

(784,)

In [18]:
W1.shape

(784, 50)

In [19]:
W2.shape

(50, 100)

In [20]:
W3.shape

(100, 10)

In [21]:
x, t = get_data()
network = init_network()

batch_size = 100
accuracy_cnt = 0

for i in range(0, len(x), batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = predict(network, x_batch)
    p = np.argmax(y_batch, axis=1)
    accuracy_cnt += np.sum(p == t[i:i+batch_size])
    
print("Accuracy:" + str(float(accuracy_cnt) / len(x)))

Accuracy:0.9352
